name: release-chart
on:
  push:
    tags: '*'

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: mnorrsken/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: .
          charts_url: https://mnorrsken.github.io
          owner: mnorrsken
          repository: charts
          branch: master